name: py2
channels:
  - remenska
dependencies:
  - ipython-notebook=4.0.4
  - matplotlib=1.4.3
  - numpy=1.10.1
  - pandas=0.17.0
  - python=2.7
  - root=5.34.32
  - root_numpy=4.3.0
  - scikit-learn=0.16.1
  - scipy=0.16.0
  - six=1.10.0
  - theano=0.7.0
  - bokeh=0.10
  - pip:
    - neurolab==0.3.5
    - theanets==0.6.2
    - pybrain==0.3
    - mpld3==0.2